project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - project-log.qmd
    - wikidata.qmd
    - wikidata-item.ipynb
  

metadata:
  author:
    - name: "Betty Quiala"
      orcid: "0009-0005-4668-0886"
      email: "betty-andrade.quiala@stud.hs-hannover.de"

website:
  title: "BIM Prototype 02"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project-log.qmd
        text: Project Log
      - href: wikidata.qmd
        text: Wikidata
      - href: wikidata-item.ipynb
        text: Item Profile



format:
  html:
    theme: cosmo
    toc: true

execute:
  freeze: auto
